version: '2'
services:
    registro-app:
        image: registro
        external_links:
            - registro-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/registro?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    registro-mysql:
        extends:
            file: mysql.yml
            service: registro-mysql
